# Generated by Django 5.2 on 2025-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercici',
            name='solucio_codi',
            field=models.TextField(blank=True, null=True, verbose_name='Solució en codi'),
        ),
    ]
