# Generated by Django 5.2 on 2025-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0002_exercici_solucio_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercici',
            name='tipus',
            field=models.CharField(choices=[('codi', 'Codi'), ('test', 'Test'), ('text', 'Text lliure'), ('exe', 'Execució de codi')], max_length=20, verbose_name="Tipus d'exercici"),
        ),
    ]
