# Generated by Django 5.2 on 2025-04-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0003_alter_exercici_tipus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercici',
            name='tipus',
            field=models.CharField(choices=[('codi', 'Escriure codi'), ('test', 'Tipus test'), ('ia', 'Correcció amb IA'), ('exe', 'Execució de codi')], max_length=20, verbose_name="Tipus d'exercici"),
        ),
    ]
