# Generated by Django 5.2 on 2025-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0004_alter_exercici_tipus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercici',
            name='solucio_codi',
        ),
        migrations.AddField(
            model_name='exercici',
            name='solucio_codi_1',
            field=models.TextField(blank=True, null=True, verbose_name='Solució en codi 1'),
        ),
        migrations.AddField(
            model_name='exercici',
            name='solucio_codi_2',
            field=models.TextField(blank=True, null=True, verbose_name='Solució en codi 2'),
        ),
    ]
