# Generated by Django 5.2 on 2025-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0005_remove_exercici_solucio_codi_exercici_solucio_codi_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercici',
            name='solucio',
            field=models.TextField(blank=True, null=True, verbose_name='Solució correcta'),
        ),
    ]
