# Generated by Django 5.2 on 2025-04-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0006_alter_exercici_solucio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercici',
            name='codi_a_completar',
            field=models.TextField(blank=True, null=True, verbose_name='Codi a completar'),
        ),
    ]
