# Generated by Django 5.2 on 2025-04-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0007_exercici_codi_a_completar'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='subnom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subnom del curs'),
        ),
    ]
