# Generated by Django 5.2 on 2025-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0008_curs_subnom'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercici',
            name='taula',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercici',
            name='tipus',
            field=models.CharField(choices=[('codi', 'Escriure codi'), ('completar', 'Completar codi'), ('test', 'Tipus test'), ('ia', 'Correcció amb IA'), ('exe', 'Execució de codi')], max_length=20, verbose_name="Tipus d'exercici"),
        ),
    ]
