# Generated by Django 5.2 on 2025-05-04 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0009_exercici_taula_alter_exercici_tipus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasPractic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(default='Cas pràctic', max_length=255, verbose_name='Títol del cas pràctic')),
                ('descripcio', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('tipus', models.CharField(choices=[('excel', 'Excel'), ('sql', 'SQL'), ('python', 'Python')], max_length=20, verbose_name='Tipus')),
                ('enllac', models.URLField(verbose_name='Enllaç')),
                ('enllac_resultat', models.URLField(verbose_name='Enllaç')),
                ('text_boto', models.CharField(default='Accedir al cas pràctic', max_length=100, verbose_name='Text del botó')),
                ('capitol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cas_practic', to='app_django.capitol', verbose_name='Capítol')),
            ],
            options={
                'verbose_name': 'Cas pràctic',
                'verbose_name_plural': 'Casos pràctics',
            },
        ),
    ]
