# Generated by Django 5.2 on 2025-05-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0010_caspractic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caspractic',
            name='tipus',
        ),
        migrations.AlterField(
            model_name='caspractic',
            name='enllac_resultat',
            field=models.URLField(verbose_name='Enllaç del resultat'),
        ),
    ]
